navbar:
  blog_title: Xor7 Studio's Blog
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2
index:
  banner_img: /img/banner.jpg
  slogan:
    enable: true
    text: 这里是 Xor7 工作室的团队博客喵
archive:
  banner_img: /img/banner.jpg
category:
  banner_img: /img/banner.jpg
tag:
  banner_img: /img/banner.jpg
about:
  banner_img: /img/banner.jpg
  avatar: /img/avatar.png
  name: "Xor7 Studio"
  intro: "一个奇奇怪怪的工作室"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Xor7Studio', tip: 'GitHub' }
footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a><br/>
    <a>本站点 Banner 图片版权归其合法所有者所有，包括但不限于 Sega、Colorful Palette 和 Crypton。</a>
  '
post:
  banner_img: /img/banner.jpg
  meta:
    author:
      enable: true
    date:
      enable: true
    wordcount:
      enable: true
      format: "{} 字"
    min2read:
      enable: true
      format: "{} 分钟"
    views:
      enable: false
      source: "leancloud"
      format: "{} 次"

favicon: /img/icon.webp